name: ubuntu package install
description: install required packages and cache apt downloads
runs:
    using: "composite"
    steps:
        - name: root suid tar for apt caching
          run:  sudo chmod u+s /bin/tar
          shell: bash

        - name: apt cache pull
          uses: actions/cache/restore@v5
          with:
            path: /var/cache/apt
            key:          xserver-apt-cache-${{ hashFiles('.github/scripts/ubuntu/install-pkg.sh') }}-v2
            restore-keys: xserver-apt-cache-

        - name: pkg install
          run:  sudo .github/scripts/ubuntu/install-pkg.sh
          shell: bash

        - name: apt cache push
          uses: actions/cache/save@v5
          with:
            path: /var/cache/apt
            key:          xserver-apt-cache-${{ hashFiles('.github/scripts/ubuntu/install-pkg.sh') }}-v2-${{ github.run_id }}
