#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Enrico Weigelt, metux IT consult <info@metux.net>

err() {
    echo "$0: $*"
}

[ "$GITHUB_REPOSITORY" ] || err "missing variable GITHUB_REPOSITORY"

TITLE=$(git tag -l --format='%(contents)' $tag)

echo "tag=$tag"
echo "title=$TITLE"

gh release create "$tag" \
        --repo="$GITHUB_REPOSITORY" \
        --title="$tag" \
        --generate-notes
